### ISSUE TITLE
Solutions not detected using VS2013 Pro

### ISSUE THREAD

**Issue by vertigo-cpp** [usysware/dpack#4]
Hi,

Firstly I'd like to say thanks for providing such a great extension for free.

When I try to open the code browser from a solution within VS2013 Pro I get the following message:

![1](https://user-images.githubusercontent.com/58335304/69873616-bb0da880-12b0-11ea-9ab2-b75e32af2265.png)

The solution browser opens successfully but appears empty:

![2](https://user-images.githubusercontent.com/58335304/69873624-c19c2000-12b0-11ea-8490-caa0d67cf525.png)

I have tried creating new solution and existing ones, which doesn't appear to make a difference.

I am running version 3.12.4. Please let me know if I can provide any more info.

All the best!

J

**Comment by usysware** [comment]
Hi there. while the latest version's compatible with Visual Studio 2013, it is largely no longer supported. The oldest currently supported version is Visual Studio 2017. It's a bit confusing, I know, so let me expand on that. I basically develop on VS 2017 with testing taking place on VS 2017 and VS 2019. Extension manifest is setup to be VS 2013 - 2019 compatible though. I no longer have VS 2013 and VS 2015 test environments setup. I may need to double check that is not the problem.

Having said that, I can speculate as to what the issue is. You didn't say what the project type or development language is btw... Anyways, DPack's Code Browser "understands" code files, ie files which are setup to compile and thus ones that have extensibility code model available, and the ones which are part of the loaded project. So if you were to open a stand alone file like .cs from Windows Explorer or one that is part of the project but whose build action is set to None, you'd get that message.

If you were to create a new console C# project, does Code Browser work on any of the .cs files?

**Comment by usysware** [comment]
Double checked it and it looks like DPack works fine with standard VS C# projects for instance. So it must've truly been a standalone or non compilable file that you opened. Extensibility code model that DPack relies on is imho its strength, which allows me to supports multiple VS languages, but also a downside that you ran into. I have considered switching to Roslyn APIs to combat just that issue but then it'd limit it to just 2 languages only - C# and VB with C++ being out. So things stay as is for now.

**Comment by usysware** [comment]
Feel to follow up if you have any other questions.
