### ISSUE TITLE
"collection file information" 

### ISSUE THREAD

**Issue by zythra** [usysware/dpack#7]
DPack Rx Version 4.0.0.24, VS 2019

When opening the file browser, the "Code Browser's collection file information" dialog pops up every single time and in most projects I'm working in it takes several seconds for it to go away.  This wasn't an issue in pre-Rx releases, so it seems to be unique to Rx.  Any chance it could cache the file information to make it less disruptive when using the file browser?

![image](https://user-images.githubusercontent.com/25746301/76013628-7c057980-5ed5-11ea-8547-dbd786a05113.png)

**Comment by usysware** [comment]
Hi there.

Yeah, it's shown if browser window takes close to a second to spin up (an arbitrary # chosen by me). The intent there is to let the user know something is taking place as oppose to basically nothing. The difference between old DPack and new DPack Rx is that in my testing WPF appears to be slower to come up just a ted, which is why it that cancellable window was added in the first place.

I have not seen any significant delays vs old DPack in my internal testing and day to day DPack Rx use. If I were to guess w/o further investigation it could any one of the following:
* related to the size of the file and # of code members in that particular file
* an issue processing your project type
* a regression in DPack Rx
* etc

Is there any way for you to isolate it in a reproducible test case and upload it for me? Also, if you could add the log file point out file in question that would help as well. Thanks.

**Comment by zythra** [comment]
Hey Sergey, thanks for the response.  I'll see what I can do to put together a solution where I can replicate it for you.  I was just trying it out on a few different files and it's definitely more pronounced in larger files.  It might take me some time to get a solution over to you, I'll try to get one put together in the next week.

**Comment by usysware** [comment]
Thanks! If you could post DPack's log file ahead of that, it might give me a chance to sip through that to see if anything stands out.

**Comment by zythra** [comment]
Sergey, sorry man, I haven't had a chance to follow up on this.  I was thinking about it yesterday and realized I haven't really noticed it much anymore.  Whether that's because it was environmental or because I've just gotten used to it I'm not sure.  Either way, if you would like, go ahead and close this issue for now.  If I notice it significantly again I'll grab a log file and get it over to you.

**Comment by usysware** [comment]
Thanks for letting me know.

**Comment by usysware** [comment]
I've reconsidered. Lets keep it open for a while. I'll do more investigation to see if I dig anything up.

**Comment by usysware** [comment]
File Browser appears to be noticeably faster in my test version now. I'm gonna switch gears to Code Browser now as I think it could use some TLC as well.

**Comment by usysware** [comment]
Code Browser appears to be marginally faster now too, particularly when invoking filtered member list, ie Methods or Properties only as oppose to All members.

I'll try wrapping it up in the next couple of days and pushing another beta out. Thanks.

**Comment by usysware** [comment]
New version is up. Let me know how it works for you. Thanks.
