### ISSUE TITLE
VS2017 could not find the shortcut key for DPack Rx

### ISSUE THREAD

**Issue by ErQing** [usysware/dpack#9]
Plug-ins work well, But VS2017 could not find the shortcut key for DPack Rx

**Comment by usysware** [comment]
Which particular DPack's feature you couldn't find the shortcut for?

You'd first let it assign the default shortcut keys for you or head over to Tools|Options, DPack|General page, and select Assign Keyboard Shortcuts. After that for bookmarks you'd right click on the open file's window to see bookmark shortcut keys, or select Tool|DPack menu for other feature shortcut keys (solution has to be loaded for context sensitive items to be shown). Hope this helps.

**Comment by ErQing** [comment]
Thank you for your reply.

I clicked "Tools|Options" - "DPack|General page" - "Assign Keyboard Shortcuts", but I didn't know what keyboard shortcuts were bound to.
I wanted to use shortcuts like "ALT+U" to open DPack Rx's file browser, but I searched a lot and tried a lot of shortcuts, but I still couldn't figure out the file browser's shortcut.
The plugin works very well, but if you can't open the file browser with a shortcut key, it will greatly reduce the efficiency of the search.

**Comment by usysware** [comment]
Are you saying Alt-U still didn't work event after you selected Assign Keyboard Shortcuts and let it do its job?

**Comment by ErQing** [comment]
Oh, You finally got what I meant.

Yes, I have tried many times, using "ALT+U" doesn't work, my IDE is VS2017.
Maybe some other software has occupied the shortcut key, I don't know how to deal with this problem, so I wonder if DPack can customize the shortcut key and so on.

**Comment by usysware** [comment]
I see. Try assigning the shortcuts again, OK tool|options dialog and check if it works or not. If it still doesn't work, open the same Tools|Options dialog, select Open Log Folder and post your copy of DPackRx.log here for me to take a look at. Thanks.

**Comment by ErQing** [comment]
[DPackRx 1.log](https://github.com/usysware/dpack/files/5025946/DPackRx.1.log)
[DPackRx.log](https://github.com/usysware/dpack/files/5025947/DPackRx.log)
This is log.

**Comment by usysware** [comment]
Thanks for the log. Looks like shortcut assignment's failing for you. I suspect it's internalization related issue. Looking into working around it here. I'll post when/if I have it figured out.

**Comment by ErQing** [comment]
Thank you.

I tried my new computer at home yesterday.
The environment is VS2019, which also encounters the same problem.
So I think this problem is common and easy to repeat.
Plugins are my favorite, and if you fix them, they're the real tools.

Waiting for future updates.

**Comment by usysware** [comment]
Give attached test version a try and let me know if it works or not please. It's a very short lived beta version. Thanks.

[DPackRx-4.0.0.30.vsix.zip](https://github.com/usysware/dpack/files/5044557/DPackRx-4.0.0.30.vsix.zip)

**Comment by ErQing** [comment]
Cool.

The shortcut keys are working properly.

**Comment by usysware** [comment]
FYI, there is a new version out incorporating keyboard shortcut assignment patch. Thanks for reporting it.

**Comment by ErQing** [comment]
You are welcome.

The tool is easy to use, as a user can help the tool to do better, I also feel a sense of accomplishment.
There was so little publicity for the tool that I searched long and hard to find it. It was like finding a treasure.

However, the tool still has a bit of a drawback in that it cannot search for definitions globally.
Currently the search definition can only be searched in the current script, which is too limited as a search tool.
If you have the time, I'd like to support global search definitions, because that's what defining search really means.

**Comment by usysware** [comment]
Thanks. There is an older non-OS version of DPack Rx simply called DPack out there too. It's quite a bit more popular:
https://marketplace.visualstudio.com/items?itemName=SergeyM.DPack-16348
That older version is basically dead and no longer maintained, including future versions of VS.

That older version supports feature called Solution Browser, which is a combination of File Browser and Code Browser. It basically searches for qualified members across the entire solution. If you launch it for the 1st time it takes a while for it to process the solution, especially if solution is quite large. Performing that operation on every Solution Browser dialog invocation is totally counter productive imho. So that older version caches the solution information on 1st use. Of course, cache is only good if it stays updated. So now, it has to keep tracking of all the changes in the background to get there. That is the part I don't like. Key development principals of my extensions are: no impact on dev environment, and fire-and-forget approach, ie once dialog you invoke closes your interaction with DPack is done. Older DPack version had added Solution Browser cache persistence to speed it up, "toolwindow mode" etc. I don't intend to go that route as it would/could impact dev environment. I might consider resurrecting Solution Browser but I'd have to be convinced it is worth it. Toolwindow mode is definitely not coming back.

I use new DPack Rx version daily and haven't found needing a solution wide feature. Combination of both File and Code Browser get me there just fine.

**Comment by ErQing** [comment]
Ok, i see.
That makes sense.
